"""
Build industry exam JSON with correct answers merged from Excel.
Outputs: scripts/industry_combined.json
"""
import fitz
import openpyxl
import re
import json
import pathlib

DOCS = pathlib.Path(r'c:\Users\Ny\Downloads\Documents')
EXCEL = pathlib.Path(r"c:\Users\Ny\Downloads\answersinSpecialEPSTOPIK\Work related questions's answers in Special EPS-TOPIK(PDF).xlsx")
OUT = pathlib.Path(__file__).parent.parent / 'src' / 'data'
OUT.mkdir(exist_ok=True)

# PDF key → (filename, Excel sheet name, labelKr, labelLo)
PDFS = {
    'metal':       ('Metal.pdf',                  'Metal',                    '금속·금속제품',     'ໂລຫະ'),
    'electronics': ('ElectronicsElectricity.pdf', 'Electronics, Electricity', '전기·전자',        'ໄຟຟ້າ·ອີເລັກໂທຣນິກ'),
    'food':        ('Food Related.pdf',            'Food Related',             '식품 제조',        'ອາຫານ'),
    'machinery':   ('MachineryMolding.pdf',        'Machinery, Molding',       '기계·금형',        'ເຄື່ອງຈັກ'),
    'pulpwood':    ('PulpPaperWood.pdf',           'Pulp, Paper, Wood',        '목재·종이',        'ໄມ້·ເຈ້ຍ'),
    'rubber':      ('RubberPlastic.pdf',           'Rubber, Plastic',          '고무·플라스틱',    'ຢາງ·ພລາສຕິກ'),
    'textile':     ('TextileSewing.pdf',           'Textile, Sewing',          '섬유·의복',        'ສິ່ງທໍ·ເຄື່ອງນຸ່ງ'),
}

SYMBOL_TO_IDX = {'①': 0, '②': 1, '③': 2, '④': 3}

def load_answers(excel_path, sheet_name):
    """Load answer key from Excel sheet. Returns dict {q_num: correct_idx}"""
    wb = openpyxl.load_workbook(str(excel_path))
    ws = wb[sheet_name]
    answers = {}
    for row in ws.iter_rows(min_row=3, values_only=True):
        # Each row has up to 4 groups: (q, a, q, a, q, a, q, a)
        cells = [c for c in row if c is not None]
        i = 0
        while i + 1 < len(cells):
            q = cells[i]
            a = cells[i + 1]
            if isinstance(q, int) and isinstance(a, str):
                a_clean = a.strip()
                idx = SYMBOL_TO_IDX.get(a_clean, -1)
                if idx == -1:
                    # Try first char
                    idx = SYMBOL_TO_IDX.get(a_clean[0] if a_clean else '', -1)
                answers[q] = idx
            i += 2
    return answers

def extract_questions(pdf_path):
    doc = fitz.open(str(pdf_path))
    full_text = ''
    for page in doc:
        full_text += page.get_text() + '\n'

    # Normalize whitespace within lines but preserve newlines
    lines = [re.sub(r'[ \t]+', ' ', l) for l in full_text.split('\n')]
    full_text = '\n'.join(lines)

    questions = []
    # Split by question number at start of line
    parts = re.split(r'\n(?=\d{1,3}\. )', full_text)

    for part in parts:
        part = part.strip()
        if not part:
            continue
        m = re.match(r'^(\d{1,3})\.\s+(.+)', part, re.DOTALL)
        if not m:
            continue
        q_num = int(m.group(1))
        body = m.group(2).strip()

        first_opt_pos = body.find('①')
        if first_opt_pos == -1:
            continue

        q_text = body[:first_opt_pos].strip()
        q_text = re.sub(r'\s+', ' ', q_text).strip()
        if not q_text:
            continue

        opts_raw = body[first_opt_pos:]
        opt_pattern = re.compile(r'([①②③④])\s*(.+?)(?=[①②③④]|$)', re.DOTALL)
        opts_found = opt_pattern.findall(opts_raw)

        if len(opts_found) < 2:
            continue

        options = []
        for sym, opt_text in opts_found:
            opt_clean = re.sub(r'\s+', ' ', opt_text).strip()
            options.append(opt_clean)

        while len(options) < 4:
            options.append('-')
        options = options[:4]

        questions.append({
            'num': q_num,
            'question': q_text,
            'options': options,
            'correctIndex': 0,
        })

    return questions

def main():
    all_industries = []

    for key, (filename, sheet, label_kr, label_lo) in PDFS.items():
        pdf_path = DOCS / filename
        print(f'Processing {filename}...')

        questions = extract_questions(pdf_path)
        answers = load_answers(EXCEL, sheet)

        # Apply answers
        applied = 0
        for q in questions:
            idx = answers.get(q['num'], -1)
            if idx >= 0:
                q['correctIndex'] = idx
                applied += 1

        print(f'  {len(questions)} questions, {applied} answers matched')

        all_industries.append({
            'key': key,
            'labelKr': label_kr,
            'labelLo': label_lo,
            'questions': questions,
        })

    # Write JS data file
    out_path = OUT / 'industryData.js'
    lines = [
        '// Auto-generated by build_industry_data.py',
        f'// 7 industries, {sum(len(x["questions"]) for x in all_industries)} questions total',
        '',
        'export const INDUSTRY_CATEGORIES = [',
    ]
    for ind in all_industries:
        lines.append(f'  {{ key: {json.dumps(ind["key"])}, labelKr: {json.dumps(ind["labelKr"])}, labelLo: {json.dumps(ind["labelLo"])} }},')
    lines.append('];')
    lines.append('')
    lines.append('export const INDUSTRY_QUESTIONS = {')
    for ind in all_industries:
        lines.append(f'  {json.dumps(ind["key"])}: [')
        for q in ind['questions']:
            entry = {
                'num': q['num'],
                'q': q['question'],
                'opts': q['options'],
                'ans': q['correctIndex'],
            }
            lines.append(f'    {json.dumps(entry, ensure_ascii=False)},')
        lines.append('  ],')
    lines.append('};')
    lines.append('')

    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f'\nWrote {out_path}')
    total = sum(len(x['questions']) for x in all_industries)
    print(f'Total: {len(all_industries)} industries, {total} questions')

if __name__ == '__main__':
    main()
