"""
Merge Book 1 (ch06-ch30) and Book 2 (ch31-ch59) vocab JSON files
into a single src/data/vocabData.js file with clean data.
"""
import json, re, pathlib, unicodedata

ROOT = pathlib.Path(__file__).parent.parent

def is_lao(text):
    """Check if text contains Lao unicode characters."""
    for ch in text:
        if '\u0E80' <= ch <= '\u0EFF':
            return True
    return False

def is_sentence(text):
    """Heuristic: likely a full sentence rather than a single vocab word."""
    # Long text (>25 chars in Korean) or contains verb endings common in sentences
    if len(text) > 30:
        return True
    # Ends in typical sentence patterns
    if re.search(r'(입니다|이에요|에요|습니다|ㅂ니까|세요|요\.|니다\.)$', text):
        return True
    return False

def clean_meaning(meaning):
    """Remove extra whitespace, newlines."""
    meaning = re.sub(r'\s+', ' ', meaning).strip()
    return meaning

def load_and_clean(json_path):
    with open(json_path, encoding='utf-8') as f:
        chapters = json.load(f)
    
    cleaned = []
    for ch in chapters:
        words = []
        seen_words = set()
        for w in ch['words']:
            word = w['word'].strip()
            meaning = clean_meaning(w.get('meaning', ''))
            img = w.get('img', '')
            
            # Skip empty words
            if not word:
                continue
            # Skip duplicate words in same chapter
            if word in seen_words:
                continue
            # Skip words that are full Korean sentences
            if is_sentence(word):
                continue
            # Skip "(no translation)" or empty meaning unless word itself is useful
            if not meaning or meaning == '(no translation)':
                meaning = ''
            # Skip entries with only English (no Lao) - keep Lao ones
            # But allow words even if meaning is empty (still show the image+word)
            # Just skip if meaning is clearly English-only and not Lao
            if meaning and not is_lao(meaning) and re.match(r'^[A-Za-z\s/\(\)\.,]+$', meaning):
                meaning = ''  # Remove English-only meanings
            
            # Skip items that are grouped label lines (multiple words in one item)
            # e.g. "사과 오렌지 포도 수박" - multiple space-separated Korean words
            parts = word.split()
            if len(parts) >= 4 and all(re.match(r'^[가-힣]+$', p) for p in parts[:4]):
                continue
            
            seen_words.add(word)
            words.append({'word': word, 'meaning': meaning, 'img': img})
        
        if words:
            cleaned.append({
                'chapter': ch['chapter'],
                'title': ch['title'],
                'titleKr': ch.get('titleKr', ''),
                'titleLo': ch.get('titleLo', ''),
                'words': words,
            })
    return cleaned

def main():
    book1 = load_and_clean(ROOT / 'scripts' / 'vocab_data_book1.json')
    book2 = load_and_clean(ROOT / 'scripts' / 'vocab_data_all.json')
    
    all_chapters = book1 + book2
    all_chapters.sort(key=lambda c: c['chapter'])
    
    total_words = sum(len(c['words']) for c in all_chapters)
    print(f"Book 1: {len(book1)} chapters, {sum(len(c['words']) for c in book1)} words")
    print(f"Book 2: {len(book2)} chapters, {sum(len(c['words']) for c in book2)} words")
    print(f"Total: {len(all_chapters)} chapters, {total_words} words")
    
    # Build JS output
    lines = [
        '// Auto-generated by make_vocab_js_combined.py',
        '// Book 1: ch06–ch30 | Book 2: ch31–ch59',
        f'// Total: {len(all_chapters)} chapters, {total_words} words',
        '',
        'export const VOCAB_CHAPTERS = [',
    ]
    
    for ch in all_chapters:
        lines.append('  {')
        lines.append(f'    chapter: {ch["chapter"]},')
        lines.append(f'    title: {json.dumps(ch["title"], ensure_ascii=False)},')
        lines.append(f'    titleKr: {json.dumps(ch["titleKr"], ensure_ascii=False)},')
        lines.append(f'    titleLo: {json.dumps(ch["titleLo"], ensure_ascii=False)},')
        lines.append('    words: [')
        for w in ch['words']:
            entry = json.dumps({'word': w['word'], 'meaning': w['meaning'], 'img': w['img']}, ensure_ascii=False)
            lines.append(f'      {entry},')
        lines.append('    ],')
        lines.append('  },')
    
    lines.append('];')
    lines.append('')
    lines.append('export const VOCAB_CATEGORIES = {')
    lines.append("  book1_work: {")
    lines.append("    label: 'เล่ม 1: งาน·สถานที่ / ວຽກ·ສະຖານທີ່',")
    lines.append("    chapters: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15],")
    lines.append("  },")
    lines.append("  book1_social: {")
    lines.append("    label: 'เล่ม 1: สังคม·ชีวิต / ສັງຄົມ·ຊີວິດ',")
    lines.append("    chapters: [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],")
    lines.append("  },")
    lines.append("  book2_general: {")
    lines.append("    label: 'เล่ม 2: ทั่วไป / ທົ່ວໄປ',")
    lines.append("    chapters: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],")
    lines.append("  },")
    lines.append("  book2_industry: {")
    lines.append("    label: 'เล่ม 2: อุตสาหกรรม / ອຸດສາຫາກຳ',")
    lines.append("    chapters: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],")
    lines.append("  },")
    lines.append("  book2_legal: {")
    lines.append("    label: 'เล่ม 2: กฎหมาย / ກົດໝາຍ',")
    lines.append("    chapters: [51, 52, 53, 54, 55, 56, 57, 58, 59],")
    lines.append("  },")
    lines.append('};')
    lines.append('')
    
    out_path = ROOT / 'src' / 'data' / 'vocabData.js'
    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f"\nWrote {out_path}")

if __name__ == '__main__':
    main()
